### ISSUE TITLE
Question: Is this Package available for .netstandard soon ?

### ISSUE THREAD

**Issue by bluekuen** [Redth/ZXing.Net.Mobile#675] opened 2018-02-08 08:02 UTC
Hello,

i'm just asking for future purposes.

Regards cunnza

**Comment by RichMcLaren** [comment] 2018-02-09 08:58
I'm already using Zxing in .netstandard project.
Try to add string below to your netstandard  *.csproj 
```<PackageTargetFallback>portable-net45+win8+wpa81+wp8</PackageTargetFallback>```

It works in my project, but only with .netstandard1.4 project

**Comment by cunnza** [comment] 2018-02-09 08:59
Great, got it working with .netStandard 2.0 ! Thank you !

**Comment by Redth** [comment] 2018-02-11 13:34
Hey folks I plan on getting .Net standard support very soon.

**Comment by knocte** [comment] 2018-03-02 08:59
Seems this is a duplicate of https://github.com/Redth/ZXing.Net.Mobile/issues/578

**Comment by jgiacomini** [comment] 2018-03-07 17:34
@Redth do you need help to migrate it in .Net standard ?

:)

**Comment by Nixon-Joseph** [comment] 2018-03-13 16:49
Looking forward to .Net Standard support. Hopefully it's available soon. The app I'm working on for my company requires Barcode scanning, and all of the other libraries are terrible. Lead doesn't like the unsupported warning on the project references, so am waiting for .Net Standard support, instead of the fallback.

**Comment by Redth** [comment] 2018-03-15 00:33
There's a 2.4.0-beta1 on nuget which has this. Please give it a try!

**Comment by jgiacomini** [comment] 2018-03-15 07:17
Thanks for all @Redth. I will try it today !

**Comment by PaulVrugt** [comment] 2018-03-15 18:54
Nice, this is the last component in our apps that doesn't have .net standard support. Finally our last warnings will be gone

**Comment by Nixon-Joseph** [comment] 2018-04-26 13:08
If you're using Visual Studio, close it, and delete the 'bin' and 'obj' folders in each project. Restart VS and try again, see if that helps.

**Comment by pradipshakya** [comment] 2018-05-06 04:26
Thanks for reply, I have fixed this issue by using old NuGet packages.

**Comment by Redth** [comment] 2020-03-13 01:41
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Closed by Redth** 2020-03-13 01:41 UTC
