### ISSUE TITLE
Qr code scaning wont work after giving permissions on android.

### ISSUE THREAD

**Issue by manoharbonala** [Redth/ZXing.Net.Mobile#717] opened 2018-04-30 15:38 UTC
HI I am using ZXing.Net.Mobile.Forms.Android (2.4.1.0) library in my app.After installation the Qr code page asking for permissions allow and deny. If I give permission as allow it is scanning continuously  but not returning any results . To get the results I have to go back and open the page again.

Can any one suggest me is there any way to scan the qr code after giving permissions.

Thanks.

**Comment by MatthewGerber** [comment] 2018-06-05 20:18
I have exactly the same problem. It does not work the first time, but it works the second time. Anyone have ideas about this?

**Comment by MatthewGerber** [comment] 2018-06-05 20:40
Adding `await Task.Delay(1000);` after manually requesting camera permissions (all prior to starting the scanner) fixes the problem.

**Comment by sbirdius** [comment] 2018-07-09 20:54
This issue was fixed in version 2.3.1 and works fine.
But in latest version 2.4.1 it does not work again...

So, if you download v2.3.1 and not the latest 2.4.1 you will be ok.

**Comment by TonyC5** [comment] 2018-10-22 20:36
The problem is fixed in 2.3.2 as well.  I reverted to 2.3.2 from 2.4.1 when I observed the behavior reported in this thread.

**Comment by knocte** [comment] 2018-11-13 08:37
Maybe I'm saying something obvious to all the people subscribed to this issue, but I thought I was affected by this bug at first, later I discovered that in a small refactoring of my app, I had removed by mistake the critical `override` bit that is mentioned in the README:

```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
{
    global::ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult (requestCode, permissions, grantResults);           
}
```

After adding this back, camera permissions started to work again immediately after granting them by the user, so I cannot reproduce this bug anymore.

**Comment by knocte** [comment] 2018-11-13 08:38
(with the last 2.4.1 version, that is)

**Comment by TonyC5** [comment] 2018-11-15 15:56
@knocte - I'm not sure I understood your post, so I'm clarifying my observation.  The problem I observed with ZXing version 2.4.1 was not due to the `override` (since I have this in both my iOS and Android specific code for my Xamarin.Forms PCL solution).  What I observed with version 2.4.1 was that the camera was enabled and scan would occur after permissions were granted, but the first scan would always fail.  During the first scan following a clean install of my app,  I needed to tap <back> (to cancel the scan) and then scan again.  The second and all subsquent scans would work fine.  After reverting to version 2.3.2, I no longer have this problem.  With 2.3.2, the first and all subsequent scans work fine.

**Comment by knocte** [comment] 2018-11-19 03:30
@TonyC5 tested. I can say that with 2.4.1 I can't reproduce this bug, I can do a successful scan immediately after granting Android's camera permissions.

**Comment by TonyC5** [comment] 2018-11-19 03:50
@knocte - are you developing an Android app or a PCL App (cross platform for Android and iOS)?  I ask, because I am observing this bug when building a PCL App with Xamarin.Forms for both Android and iOS.

**Comment by knocte** [comment] 2018-11-19 03:53
I'm developing a crossplatform (iOS, Android, ...) Xamarin.Forms app with a .NET Standard library.

**Comment by TonyC5** [comment] 2018-11-19 04:01
@knocte - Thanks!  I will retest and post results.  Maybe a recent Xamarin.Forms package update fixed the problem?

**Comment by TonyC5** [comment] 2018-11-21 17:55
@knocte - I retested and found that the ZXing version 2.4.1 problem (first scan fails after clean app install) does not work.  More specifically, on Android 6.0 where the user must first confirm use of the camera, the first scan fails after user confirms camera permission.  User must tap <back> to abort the first scan and then rescan to work-around the problem.  All subsequent scans work.  On older Android devices that do not prompt the user for camera permision, this is not a problem.  

I will revert to ZXing version 2.3.2 since the problem does not happen for me with that version.  If you have any other ideas that might explain why you don't see the 2.4.1 problem, please post here.  Thanks!

**Comment by knocte** [comment] 2018-11-21 18:10
Did your last test involve a Xamarin.Forms app or a Xamarin.Android "raw" app?

**Comment by TonyC5** [comment] 2018-11-21 19:55
Xamarin.Forms PCL build for both Android and iOS.

**Comment by DeShrike** [comment] 2019-02-21 15:50
I have the same problem, version 2.4.1, Xamarin Forms, Android.
This problem only seems to occurr when then app is installed from an APK download.
I dont see this problem if I run the app from the IDE (Start Debugging/Start Without Debugging)

Is there a fix ?

**Comment by knocte** [comment] 2019-02-21 15:53
> when then app is installed from an APK download

How about when installed from AppStore? I don't have this bug when installed from AppStore.

**Comment by aadunn** [comment] 2019-03-15 12:40
This is also happening for me on 2.4.1, I've reverted to 2.3.2 for now as well. The same bug exists when downloading from Google Play, start debugging on device, start without debugging on device.

**Comment by NightMan665** [comment] 2019-12-27 15:18
Use 2.4.1 version. Suffered half a day to defeat this issue, but only found a workaround. However, my experience may be useful for someone.

First of all - add init command into your OnCreate method of your first activity (splash for example).
`MobileBarcodeScanner.Initialize(Application);`
Then, if you trying to enable your scanner in OnResume - it will not work. I have suggestion why it so, scanner just doesn't have enough time to start camera in the same time while activity (fragment) trying perform something under the hood. Nevertheless, if you put a little delay before scanner activation code - it should works. So, I put only one line in my OnResume method before StartScan method invoked:
`await Task.Delay(500);`

**Comment by NightMan665** [comment] 2020-01-22 08:06
Colleagues, hello again. I suppose I found the solution instead of workaround, now my scanner starts every time, including first time.

Before I used a sample of code, which looks approximately like this:

```
        private ZXingScannerFragment _scanFragment;

        public override async void OnResume()
        {
            base.OnResume();

            var needsPermissionRequest = ZXing.Net.Mobile.Android.PermissionsHandler.NeedsPermissionRequest(Activity);

            if (needsPermissionRequest)
            {
                await ZXing.Net.Mobile.Android.PermissionsHandler.RequestPermissionsAsync(Activity);
            }

            if (_scanFragment == null)
            {
                _scanFragment = new ZXingScannerFragment();

                Activity.SupportFragmentManager.BeginTransaction()
                    .Replace(Resource.Id.camera_scanner_fragment, _scanFragment)
                    .Commit();
            }

            if (!needsPermissionRequest)
            {
                StartScan();
            }
        }
```

But the issue appears in moment when the app trying to commit fragment transaction and it is not enough time to start camera before fragment appears.
All you need to do is add one line after Commit(), so you'll see something like this:

`                
                Activity.SupportFragmentManager.BeginTransaction()
                    .Replace(Resource.Id.camera_scanner_fragment, _scanFragment)
                    .Commit();
                Activity.SupportFragmentManager.ExecutePendingTransactions();
`

Just in case, there is sample of my StartScan method:

```
        private void StartScan()
        {
            var opts = new MobileBarcodeScanningOptions
            {
                PossibleFormats = new List<BarcodeFormat>
                {
                    BarcodeFormat.PDF_417,
                    BarcodeFormat.QR_CODE
                },

                CameraResolutionSelector = availableResolutions =>
                {
                    foreach (var ar in availableResolutions)
                    {
                        Console.WriteLine("Resolution: " + ar.Width + "x" + ar.Height);
                    }
                    return availableResolutions[0];
                }
            };

            _scanFragment.StartScanning(result =>
            {
                // Null result means scanning was cancelled
                if (result == null || string.IsNullOrEmpty(result.Text))
                {
                    Toast.MakeText(Activity, "Scanning Cancelled", ToastLength.Long).Show();
                    return;
                }

                // Otherwise, proceed with result
                Activity.RunOnUiThread(() =>
                    {
                        Toast.MakeText(Activity, $"Scanned value: {result}", ToastLength.Long).Show();
                    }

                );
            }, opts);
        }
```

**Comment by vkreddyg** [comment] 2020-03-10 16:59
global::ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult (requestCode, permissions, grantResults);           

above single line in OnRequestPermissionsResult of  MainActivity.cs worked like a charm.. 

people might be using below faulty one...
Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
base.OnRequestPermissionsResult(requestCode, permissions, grantResults);

**Comment by vkreddyg** [comment] 2020-03-10 16:59
> Maybe I'm saying something obvious to all the people subscribed to this issue, but I thought I was affected by this bug at first, later I discovered that in a small refactoring of my app, I had removed by mistake the critical `override` bit that is mentioned in the README:
> 
> ```
> public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
> {
>     global::ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult (requestCode, permissions, grantResults);           
> }
> ```
> 
> After adding this back, camera permissions started to work again immediately after granting them by the user, so I cannot reproduce this bug anymore, with the last version, 2.4.1.

This works..

**Comment by Redth** [comment] 2020-03-14 04:30
This should be fixed in 3.0.0-beta's.  Please try and open a new issue if you still have problems.  Thanks.

**Closed by Redth** 2020-03-14 04:30 UTC

**Comment by JoaoSousa00** [comment] 2021-01-07 23:18
> global::ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult (requestCode, permissions, grantResults);
> 
> above single line in OnRequestPermissionsResult of MainActivity.cs worked like a charm..
> 
> people might be using below faulty one...
> Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
> base.OnRequestPermissionsResult(requestCode, permissions, grantResults);

This Worked perfectly for me!

**Comment by TonyC5** [comment] 2021-08-06 15:48
@JoaoSousa00 The OnRequestPermissionsResult line you posted is the only one I've ever used (and still use).  Version 2.4.1 still gives me the same problem (first scan fails), so I'm still running 2.3.2 without any problems.  I see that 3.0.0 is still in beta.

**Comment by TonyC5** [comment] 2021-08-13 16:10
I was able to solve this problem [here](https://github.com/Redth/ZXing.Net.Mobile/issues/888?_pjax=%23js-repo-pjax-container#issuecomment-898567003).  

EDIT: I just realized that my proposed solution is the same as the solution recommended by @lhughey [here.](https://github.com/Redth/ZXing.Net.Mobile/issues/888#issuecomment-634861243)
