### ISSUE TITLE
When using ZXingBarcodeImageView control, the exception thrown when BarcodeValue passed is empty.

### ISSUE THREAD

**Issue by agat366** [Redth/ZXing.Net.Mobile#782] opened 2018-09-20 11:16 UTC
Usually (especially when working with Mvvm-pattern) the value passed into the controls might not be initialized on the page initialization (loading), but setup later, or sometimes the control might be hidden (when has no value) and appears when the value obtained.

But in both cases, the control throws exception of empty data, which doesn't have much sense, as if there is no data, the control could be just empty (white space or empty Bar-code).

So, it would be much more handy not to have the exception thrown for empty values.

Thanks!

**Comment by angelru** [comment] 2018-11-02 07:13
I have the same issue:

https://github.com/Redth/ZXing.Net.Mobile/issues/763

any other solution?

**Comment by Redth** [comment] 2020-03-13 01:06
Duplicate of #763

**Closed by Redth** 2020-03-13 01:06 UTC
