### ISSUE TITLE
Press "Back" button will exit from App in Xamarin.UWP MasterDetailPage

### ISSUE THREAD

**Issue by huangjinshe** [Redth/ZXing.Net.Mobile#350] opened 2016-06-24 18:25 UTC
I'm using UWP in Xamarin.Forms.
I have a MasterDetailPage, There is a NavigationPage in the Detail. I start read the barcode, but after I press the Back button on My Lumia 640XL, it will exit from current App.

I already tried to add `NavigationCacheMode="Enabled"`  in MainWindow.xaml.  Not working.

I upload a sample file: https://drive.google.com/file/d/0Bw0uognK2ErvYmxjanJieWxhUG8/view?usp=sharing

Is there some one has real device could test it?

 Thanks.

**Comment by huangjinshe** [comment] 2016-06-27 03:34
I try to add:

```
 var scanner = new ZXing.Mobile.MobileBarcodeScanner();
scanner.CancelButtonText = "return";
scanner.TopText = "top text";
scanner.BottomText = "bottom text";
scanner.FlashButtonText = "flash";
```

for display some button on the UWP, then I don't worry about the return problem. But all not working.  even the top and bottom label not show on.

**Comment by huangjinshe** [comment] 2016-06-27 12:04
Ok, After I see the source code I found UWP never implement CancelButtonText.  
Also it will throw some exception after finish, maybe execute some method twice. lime media capture : stop preview method.
Also there is still has navigation problem after you navigate back , it's not the original page.

So I download the source code and fixed all problems.
1.Fix when finish scan stop, the mediaCapture.stopPreview() will execute more than onece problem.
2.Old UWP will always use the current mainWindow Frame, that cause a lot of problem. So I create a new Frame and replace mainWindow.Content, after finish scan just restore the original mainWindow.Content. All fine, I test it on real phone.

Now you could remove the description about add on MainWindow:
`NavigationCacheMode="Enabled"` 

3.I add a cancel button.  But If you want to use it, just need to set the `CancelButtonText`. like:

```
 var scanner = new ZXing.Mobile.MobileBarcodeScanner();
scanner.CancelButtonText = "Return";

```
That will more helpful because you don't need to press Back button on the phone, and cause some trouble.

By the way: When I submit code to GitHub, there is some commit problem, just ignore it if I submit it twice.(First time use, sorry for that)

@Redth  Please Release a new UWP and UWP.form version on Nuget, Thank you.

**Comment by Redth** [comment] 2016-07-18 20:20
Duplicate of #366

**Closed by Redth** 2016-07-18 20:20 UTC
Labels: duplicate
