### ISSUE TITLE
TopText & BottomText is not showing

### ISSUE THREAD

**Issue by KathirveluM** [Redth/ZXing.Net.Mobile#380] opened 2016-07-26 12:04 UTC
Hi,
I am trying to insert text into the scanner.TopText and scanner.BottomText with (Default ZXingScannerPage as well as  CustomScanPage) as mentioned in the sample but nothing appear on the barcode scanner page.

Kindly help me to show the texts.

**Comment by parasmk** [comment] 2016-07-29 05:21
Having same issue. Scans perfectly, but no help text!

Am using with Xamarin Forms 2.2.0.31 on Android API level 21.

**Comment by parasmk** [comment] 2016-07-29 05:36
Some help please, it's urgent!!!

**Comment by kentliaw** [comment] 2016-08-26 09:52
Yup..seems to have the same issue here.

**Comment by akadooie** [comment] 2016-09-28 13:59
Same issue here, i am using V2.1.47. Also the ShowFlashButton is always there. No impact if i set it to false.

**Comment by hmoratopcs** [comment] 2016-11-21 12:58
Duplicate of #427

**Comment by Redth** [comment] 2020-03-13 01:47
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Closed by Redth** 2020-03-13 01:47 UTC
