### ISSUE TITLE
Auto focus not working on second run

### ISSUE THREAD

**Issue by gklappe** [Redth/ZXing.Net.Mobile#287] opened 2016-03-22 23:27 UTC
When opening the scanner for a second run(thus creating a new scanner) the autofocus is having trouble focusing on far objects. After this, taking a picture with the UIImagePicker also displays this problem. If I could supply the capture device to ZXing maybe it would be solved.

iOS 8/9 and xamarin 5.10.3

**Comment by tmson90** [comment] 2016-03-30 03:55
I think the problem is you are using stopScanning method, use PauseAnalysis and ResumeAnalysis for the case you want to stop capture. Hope that helpful :)

**Comment by gklappe** [comment] 2016-03-31 11:25
On second thought maybe it's an Xamarin issue, I use the have this issue with photo's as well, but reworked it so it is more like a singleton service. Maybe there would be a similar solution to scanning,(and use the pauseAnalysis and resumeAnalysis) I will try this, but I fear it will still conflict.

Thanks for the help

**Comment by tmson90** [comment] 2016-03-31 11:38
PauseAnalysis does not stop the camera but the image will be not analysis anymore. If you want to stop and start the camera I think the solution is refresh activity or fragment itseft. It's not because the xamarin. You can check from zxingsurfaceview.cs and zxingfragment to know why stop and start scanner do not restart the camera. :)

**Comment by Redth** [comment] 2016-04-08 15:55
Duplicate of #260 which is fixed and will be included in the next release.

**Closed by Redth** 2016-04-08 15:55 UTC
