### ISSUE TITLE
Unable to scan big QR-Code

### ISSUE THREAD

**Issue by No1e** [Redth/ZXing.Net.Mobile#807] opened 2019-02-27 07:35 UTC
Dear ZXing Support,

Could you enhance your library to support scanning of bigger QR Codes

Here is an example:
![qr code](https://user-images.githubusercontent.com/25526781/53473345-76778700-3a6a-11e9-9ee4-2b72e19d691a.PNG)

Kind regards,
Novak

**Comment by knocte** [comment] 2019-03-08 04:40
Maybe this issue is a duplicate of https://github.com/Redth/ZXing.Net.Mobile/issues/624

That being said, some performance improvements have landed on the `dev` branch of this repo, which may help your device scan big QR codes. Sadly no nuget package has been published yet that includes these changes, but maybe you can try building the `dev` branch yourself and trying it out?

**Comment by Redth** [comment] 2020-03-13 01:01
3.0.0 should have these enhancements.  Sorry for the frustration with my slowness in getting back to this project.

**Closed by Redth** 2020-03-13 01:01 UTC

**Comment by se** [comment] 2021-01-26 21:57
Hi @Redth. Is there any update on this? Or anything we can help? I have tested 3.x beta but still no luck.
