### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by TheForeignMan** [Redth/ZXing.Net.Mobile#528] opened 2017-04-13 07:13 UTC
I received a crash report with the following information. I don't want to point the finger, but it seems that it is coming from the ZXing library (correct me if I'm wrong). It was found on Android 5.1, and I have been using Xamarin on Visual Studio.

I'm not sure how helpful this is, but I don't have much more to go with:

> java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2014)
	at md55109d95aac470e32f9a4031a908f0227.ZXingSurfaceView.n_onTouchEvent(Native Method)
	at md55109d95aac470e32f9a4031a908f0227.ZXingSurfaceView.onTouchEvent(ZXingSurfaceView.java:53)
	at android.view.View.dispatchTouchEvent(View.java:8838)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2196)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2196)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2196)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2196)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2196)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2196)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2610)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1779)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2853)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2571)
	at android.view.View.dispatchPointerEvent(View.java:9033)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4231)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4094)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3649)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3702)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3668)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3785)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3676)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3842)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3649)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3702)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3668)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3676)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3649)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5877)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6022)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5912)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by hmoratopcs** [comment] 2018-01-08 08:08
Possible duplicate of #429

**Comment by Redth** [comment] 2020-03-13 01:44
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Closed by Redth** 2020-03-13 01:44 UTC
