### ISSUE TITLE
UWP Sample: can't change a button Content to the result of scan.

### ISSUE THREAD

**Issue by zipgenius** [Redth/ZXing.Net.Mobile#319] opened 2016-05-06 15:12 UTC
I modified the UWP sample with this code:

async Task MessageBox(string text)
        {
            await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
            {
                this.buttonScanDefault.Content = text;
            });
            await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, async () =>
            {
                
                var dialog = new MessageDialog(text);
                await dialog.ShowAsync();
            });
            
        }

The goal is to change buttonScanDefault.Content to the text coming from a non-Continuous scan.
Each time I try, the button Content is unchanged. I can only see the result in the MessageDialog but I can't make it appear anywhere in the UI.

**Comment by chromos33** [comment] 2016-05-10 12:19
I have the Same Problem just with Xamarin and UWP Scan.
What i have found out is that in UWP when the App should switch back to the Page before the Scan Camera screen. It calls the Application Constructor again as if restarting. Your Code is still executed just that the UI it would be inserted into won't be displayed anymore since the App "restarts"

Anyone got a Solution for this?

**Comment by Redth** [comment] 2016-05-11 15:35
Duplicate of #319

**Closed by Redth** 2016-05-11 15:35 UTC
Labels: duplicate
