### ISSUE TITLE
Adding ZXing to Xamarin forms portable project

### ISSUE THREAD

**Issue by richardpike** [Redth/ZXing.Net.Mobile#343] opened 2016-06-07 14:42 UTC
The install process when adding 2.04, and 2.1-beta fails if you include the Xamarin forms PCL project.

"Could not install package 'ZXing.Net.Mobile 2.0.4.46'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

I installed it to my android project then added the references manually which has worked.

It seems the problem lies with the folder name that is generated here:
\..\packages\ZXing.Net.Mobile.2.1.0-beta1\lib

which is "portable-net45+netcore45+wp8+UAP10+MonoAndroid403+MonoTouch10+Xamarin.iOS10"

It's missing a reference which would allow the installer to work. For reference here's the folder name on the Xamarin.Forms nuget:
"portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10"

I'm afraid my knowledge is limited, so I can't tell you exactly which one needs adding.

**Comment by jenscski** [comment] 2016-06-10 12:33
I had the same problem. The problem is the profile your PCL is targeting, it's not compatible with ZXing. I changed the target of mine PCLs to profile7, but there may be other profiles that is compatible with ZXging.

I have used this web page to compare different profiles, to find out which one I need, and can use.
http://run.plnkr.co/plunks/03ck2dCtnJogBKHJ9EjY/

**Comment by Redth** [comment] 2016-07-18 19:13
Should be fixed in 2.1.0 when it's released soon.

**Closed by Redth** 2016-07-18 19:13 UTC
Labels: bug
