### ISSUE TITLE
UWP Not read in portrait.

### ISSUE THREAD

**Issue by AleBitlam** [Redth/ZXing.Net.Mobile#321] opened 2016-05-10 16:50 UTC
I have a problem with reading if the phone is set to vertical.
In order to be read I have to turn the 90 degrees barcode. it seems that the mask with the red line follows the orientation, but the reader does not read if the phone is in portrait.
I try whit Lumia 735

**Comment by Redth** [comment] 2016-05-11 15:34
Yep, there is an issue with rotation.  For now use TryHarder, or wait until it's fixed in the next stable release :)   Duplicate of #241

**Closed by Redth** 2016-05-11 15:34 UTC
Labels: duplicate

**Comment by AleBitlam** [comment] 2016-05-12 06:22
thank you, it works! sorry for the duplicate and good work!

**Comment by danieldotnet** [comment] 2017-01-04 10:15
I have this issue too, when I change while scanning the orientation from portarit to landscape, the app crash. UWP App (Win10). Thank you for fixing.
