### ISSUE TITLE
ImageSource to device Image - Xamarin Forms

### ISSUE THREAD

**Issue by nikolaynn2008** [Redth/ZXing.Net.Mobile#843] opened 2019-11-22 12:44 UTC
Good day. Please help with `<Image x:Name="generateView" Source="Sample.Png" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="2" WidthRequest="300" HeightRequest="300" BackgroundColor="Aqua"/>` to save the image on the device.
 I’m learning to program, I found a couple of examples, I don’t work, there are no errors, but they don’t save on the device either.
 Here is an example

No errors but no save
interface 

> public interface ISaveImage
> {
>     void SavePictureToDisk(ImageSource imgSrc, string Id, bool OverwriteIfExist = false);
> }

IOS 

> public async void SaveImage(ImageSource imgSrc, string id, bool overwriteIfExist = false)
>     {
>         var renderer = new StreamImagesourceHandler();
>         var photo = await renderer.LoadImageAsync(imgSrc);
> 
>         string jpgFilename = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), id + ".jpg");
> 
>         if (File.Exists(jpgFilename))
>         {
>             File.Delete(jpgFilename);
>         }
> 
>         NSData imgData = photo.AsJPEG();
>         NSError err;
>         if (imgData.Save(jpgFilename, false, out err))
>         {
>             Console.WriteLine("saved as " + jpgFilename);
>         }
>         else
>         {
>             Console.WriteLine("NOT saved as " + jpgFilename
>                                 + " because" + err.LocalizedDescription);
>         }
> 
>     }
Android
 

> public async void SaveImage(ImageSource imgSrc, string id,
>                                         bool overwriteIfExist = false)
>     {
>         var renderer = new StreamImagesourceHandler();
>         var photo = await renderer.LoadImageAsync(imgSrc, Forms.Context);
> 
>         string jpgFilename = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), id + ".jpg");
> 
>         if (File.Exists(jpgFilename))
>         {
>             File.Delete(jpgFilename);
>         }
> 
>         using (FileStream fs = new FileStream(jpgFilename, FileMode.OpenOrCreate))
>         {
>             photo.Compress(Bitmap.CompressFormat.Jpeg, 100, fs);
>         }
>      }

**Comment by Redth** [comment] 2020-03-14 04:29
Duplicate of #841

**Closed by Redth** 2020-03-14 04:29 UTC
Labels: keep
