### ISSUE TITLE
Scan second time does not work

### ISSUE THREAD

**Issue by davidbuckleyni** [Redth/ZXing.Net.Mobile#833] opened 2019-09-17 13:48 UTC
I have my code on a button whcih is in a async thread and it brings the scanner up and does it thing fine. But if i call that button from another peice of code it brings up the viewport ok and the red line but it refuses to scan.

**Comment by davidbuckleyni** [comment] 2019-09-17 13:52
09-17 14:51:26.087 D/ZXing.Net.Mobile(20924): Selected Resolution: 800x400
09-17 14:51:26.090 D/ZXing.Net.Mobile(20924): Changing Camera Orientation to: 90
09-17 14:51:26.098 I/Choreographer(20924): Skipped 44 frames!  The application may be doing too much work on its main thread.
09-17 14:51:26.104 I/OpenGLRenderer(20924): Davey! duration=997ms; Flags=1, IntendedVsync=27639388009849, Vsync=27639621343173, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=27639628296231, AnimationStart=27639628349772, PerformTraversalsStart=27639628660918, DrawStart=27640372810992, SyncQueued=27640376872816, SyncStart=27640376936618, IssueDrawCommandsStart=27640377375837, SwapBuffers=27640382866931, FrameCompleted=27640385103546, DequeueBufferDuration=2015000, QueueBufferDuration=230000, 
09-17 14:51:27.156 D/ZXing.Net.Mobile(20924): Barcode Found
09-17 14:51:27.157 D/Camera  (20924): app passed NULL surface
09-17 14:51:27.337 W/Camera-JNI(20924): callback on dead camera object

**Comment by davidbuckleyni** [comment] 2019-09-17 14:10
This is my full code example 

[code]

public async  void  BtnScanStockTakeItem_Clicked(object sender, EventArgs e)
{    

     var scanPage = new ZXingScannerPage();
     scanPage.ToggleTorch();
     scanPage.IsScanning = true;               
     await Navigation.PushAsync(scanPage);
     scanPage.OnScanResult += (result) =>
     {


      // Stop scanning
      scanPage.IsScanning = false;

      // Pop the page and show the result
      Device.BeginInvokeOnMainThread(async () =>
    {
        await Navigation.PopAsync();
    }
}
I am then calling the above from another button method lets say the saved function

private async void SaveFunction(object sender, EventArgs e)
{

        foreach (var item in transferList)
        {

            int z = await restServices.PostStockTakeTransaction(item);
        }
        Preferences.Set("StockTakeWarehouse", pickStockTake.SelectedIndex);
        WarehouseName = pickStockTake.SelectedItem.ToString();
        bool x = await DisplayAlert("Test", "Item Saved", "ReScan", "Cancel");
        if (x)
        {
             BtnScanStockTakeItem_Clicked(sender, e);
            //this is where it rescans the item
        }
 }
[/code]

**Comment by abdul-wasey** [comment] 2019-12-10 14:17
> I have my code on a button whcih is in a async thread and it brings the scanner up and does it thing fine. But if i call that button from another peice of code it brings up the viewport ok and the red line but it refuses to scan.

same here 
any workaround you have ? to solve this problem ?

**Comment by davidbuckleyni** [comment] 2019-12-10 14:55
It didn't really solve the problem but there is a camera delay option in the which allowed the user to move the phone away from the barcode in time.

**Comment by abdul-wasey** [comment] 2019-12-13 11:00
> It didn't really solve the problem but there is a camera delay option in the which allowed the user to move the phone away from the barcode in time.

Thanks for sharing thos approach

**Comment by maxima120** [comment] 2020-01-30 13:29
I have same issue. This makes this solution unusable for any serious application. If a user needs to scan several barcodes in one session which is the only use case for a real product - then this is not feasible. The amount of errors and level of frustration is going to be unbearable. 

This is reproduceable by simply adding a button "Start Scan" which changes `IsScanning` and `IsAnalyzing` to true and then changed them back to false in `OnScanResult` event handler

@Redth - please have a look. If you could point me into what could be the problem - Ill contribute a fix. I just don't know where to look. Pretty please? :)

**Comment by maxima120** [comment] 2020-01-30 14:45
Here is the solution (scroll to the end): https://github.com/Redth/ZXing.Net.Mobile/issues/659

in short - set `IsScanning` to true before 1st scan and never touch it (it kills the plugin it seems). Instead flip `IsAnalyzing` on and off when needed.

**Comment by knocte** [comment] 2020-02-25 06:29
@maxima120 can you translate your last sentence into a .diff file please?

**Comment by Redth** [comment] 2020-03-13 00:43
In 3.0.0 the IsScanning should be fixed, but yes that will cause the scanning view to actually stop/start.  IsAnalyzing is intended to keep the scanner running but not detect barcodes in it while it's false.

Please open a new issue if there are still problems with this in 3.x series.

**Closed by Redth** 2020-03-13 00:43 UTC
