### ISSUE TITLE
Is IsScanning bindable?

### ISSUE THREAD

**Issue by stesvis** [Redth/ZXing.Net.Mobile#848] opened 2019-11-30 22:24 UTC
I see that IsScanning in ZXingScannerView is a bindable property, but it does not implement the PropertyChanged event.

So when I bind it to a ViewModel property it works on load, but when I change its value it won't apply to the view.

**Comment by abdul-wasey** [comment] 2019-12-10 14:15
> I see that IsScanning in ZXingScannerView is a bindable property, but it does not implement the PropertyChanged event.
> 
> So when I bind it to a ViewModel property it works on load, but when I change its value it won't apply to the view.

IsScanning Value is not changing even in the code-behind file. When page reload then it's value set from Xaml Compilation

**Comment by Redth** [comment] 2020-03-14 04:29
Duplicate of #710

**Closed by Redth** 2020-03-14 04:29 UTC
Labels: keep
