### ISSUE TITLE
Iphone 11 throwing Unexpected AVMetadataObjectType: humanBody error

### ISSUE THREAD

**Issue by jmattia** [Redth/ZXing.Net.Mobile#837] opened 2019-10-23 18:04 UTC
When calling the Scan method linked below with the second parameter(useAVCaptureEngine) set to true we started getting an ArgumentOutOfRangeException throwing "Unexpected AVMetadataObjectType: humanBody" when called on any iphone 11's

https://github.com/Redth/ZXing.Net.Mobile/blob/master/Source/ZXing.Net.Mobile.iOS/MobileBarcodeScanner.cs#L106

It seems iOS 13 introduced some new AVMetadataObject types that are missing in xamarin.
(last three) -
https://developer.apple.com/documentation/avfoundation/avmetadataobject/objecttype

**Comment by jonathanfontaine** [comment] 2019-10-31 16:17
Same problem here, here's the full callstack :

`AVMetadataObject.ObjectToEnum (Foundation.NSString obj)
AVMetadataObject.ArrayToEnum (Foundation.NSString[] arr)
AVCaptureMetadataOutput.get_AvailableMetadataObjectTypes ()
AVCaptureScannerView.SetupCaptureSession ()
AVCaptureScannerView.<StartScanning>b__36_0 ()
NSActionDispatcher.Apply ()
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr,intptr,intptr,bool)
NSObject.InvokeOnMainThread (System.Action action)
AVCaptureScannerView.StartScanning (System.Action1[T] scanResultHandler, ZXing.Mobile.MobileBarcodeScanningOptions options)
QrCodeScannerBaseViewController7[TView,TViewModel,TFactory,TViewKind,TDatabaseManager,TLogManager,TId].ViewDidAppear (System.Boolean animated) in <2b85b7c60156495f9c98cd891385cafc#b444b8bb461b4e30858e7d3cdaa094ab>:0
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)`

**Comment by mondayuk** [comment] 2019-12-03 13:12
I have found a workaround for this which can be seen here #846

**Comment by Redth** [comment] 2020-03-13 00:41
Duplicate of #846

**Closed by Redth** 2020-03-13 00:41 UTC
