### ISSUE TITLE
[Android Only] ZXingBarcodeImageView can't access an already disposed object.

### ISSUE THREAD

**Issue by thetrust3343** [Redth/ZXing.Net.Mobile#602] opened 2017-08-10 09:22 UTC
When I open my page containing a ZXingBarcodeImageView in my navigation and I want to go back my app crashes with the exception that it can't access an already disposed object (Android ImageView)

**Comment by voydz** [comment] 2017-08-21 08:26
possibly duplicate of #596

**Comment by marthinch** [comment] 2018-09-24 03:29
Anyone fix this issue? I've got similar issue. I'm using 2.4

**Comment by marthinch** [comment] 2018-09-25 02:43
I try to put my method (generate barcode) on constructor and it works fine in my navigation.
Note : Don't put your method to generate barcode on OnAppearing, because it will throw exception "can't access an already disposed object (Android ImageView)"

**Comment by Redth** [comment] 2020-03-13 01:43
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Closed by Redth** 2020-03-13 01:43 UTC
