### ISSUE TITLE
[UWP] Hardware back button exit application

### ISSUE THREAD

**Issue by WiliamGP** [Redth/ZXing.Net.Mobile#362] opened 2016-07-16 09:16 UTC
When I'm on the scanner screen and click on the back of the phone hardware button, the application is closed. Is there any solution for this? Best Regards!

**Comment by Redth** [comment] 2016-07-18 20:20
Duplicate of #366

**Closed by Redth** 2016-07-18 20:20 UTC

**Comment by F1nZeR** [comment] 2016-07-19 04:51
@WiliamGP you need to add custom hardware back button handler in your app, for example:

```cs
SystemNavigationManager.GetForCurrentView().BackRequested += (sender, e) =>
{
   Frame rootFrame = Window.Current.Content as Frame;
   if (!e.Handled && rootFrame != null && rootFrame.CanGoBack)
   {
      e.Handled = true;
      rootFrame.GoBack();
   }
}
```

**Comment by WiliamGP** [comment] 2016-08-15 23:26
@F1nZeR thanks, I add this code and works for me. Thank you. Best regards! :)
