### ISSUE TITLE
Zxing Net Mobile for Xamarin Forms Flash (torch) button can't be hidden?

### ISSUE THREAD

**Issue by tekken1234** [Redth/ZXing.Net.Mobile#388] opened 2016-08-02 09:23 UTC
I am using a custom button for torch on my app scanner page, but weird, 
even i set "ShowFlashButton = false " in overlay but it still appear?

many thanks
![2016-08-02 17 27 24](https://cloud.githubusercontent.com/assets/8185351/17323881/6d6cf97e-58d6-11e6-9821-9888b4bb1c6c.jpg)

**Comment by fredrikhaglund** [comment] 2016-08-04 09:34
Could you us some code how you create to View/Page and send in the options? What version of the nuget package are you using?

**Comment by timahrentlov** [comment] 2016-08-24 11:18
I have the same problem on both iOS and Android. The flash button is always displayed. 
I'm using ZXing.Net.Mobile nuget 2.1.45 on XF2.3.2.118.

It does not matter wether I'm doing it in code or in XAML like:

	
	<zxing:ZXingScannerView x:Name = "scannerView" Grid.Row = "0" /> 
	<zxing:ZXingDefaultOverlay ShowFlashButton = "false" TopText = "Hold your phone up to the barcode"  BottomText = "Scanning will happen automatically" Grid.Row = "0"/>

	
	<BoxView Style="{StaticResource horizontalBoldDivider}" Grid.Row = "1" />

	
	<local:StyledListView HasUnevenRows = "true" ItemsSource = "{Binding Parcels}" ItemTemplate = "{StaticResource parcelTemplate}" Grid.Row = "2"/>

**Comment by akadooie** [comment] 2016-10-06 08:31
I am having the same problem here. "ShowFlashButton = false" but it still appears on the overlay, any solutions/workarounds yet?

**Comment by nurhasyim354** [comment] 2016-11-10 05:26
I have same problem in both android and IOS. Any suggestion to solve this issue?

**Comment by hmoratopcs** [comment] 2016-11-21 12:43
Possible duplicate of #427

**Comment by Redth** [comment] 2020-03-13 01:47
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!

**Closed by Redth** 2020-03-13 01:47 UTC
