### ISSUE TITLE
UWP wont scan 1d barcodes

### ISSUE THREAD

**Issue by silverdex** [Redth/ZXing.Net.Mobile#300] opened 2016-04-12 18:26 UTC
I'm running the sample app on a Lumia 950XL which seems to scan QR codes without a problem but won't scan 1D barcodes.  I've even tried changing the PossibleFormats option to All_1D but it still doesn't work.

I'm not sure if I'm missing something obvious here.

**Comment by danieldotnet** [comment] 2016-04-24 10:53
For me it does not work either with Universal App Win10 (ALL_1D)
Only QR-Code reading works well.

**Comment by danardelean** [comment] 2016-05-03 05:18
Use TryHarder property and set it to true and it will work with 1D also

**Comment by danieldotnet** [comment] 2016-05-07 11:44
Thank you very much, it works fine now.

**Comment by Redth** [comment] 2016-05-11 15:33
Yep, the rotation is currently a problem... Duplicate of #241

**Closed by Redth** 2016-05-11 15:33 UTC
